name: ci_meson

on:
  push:
    paths:
      - "**.c"
      - "**.h"
  pull_request:
    paths:
      - "**.c"
      - "**.h"
  workflow_dispatch:

jobs:

  linux:
    runs-on: ubuntu-latest
    steps:
    - name: install-libasound2-dev
      run: apt install libasound2-dev     
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
    - uses: BSFishy/meson-build@v1.0.3
      with:
        action: build
